name: API Tests
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Run Tests
      run: php artisan test
